(5 + 10 * 2 + 15 / 3) * 2 + -10;
(10 + 2) * 30 == 300 + 20 * 3;

if 5 < 10 {
  if 1 == 2 {
    15
  } else {
    5 + true;
  }
} else if 5 > 10 {
    5
} else {
    0
}

if 5 < 10 {
  if 1 == 2 {
    15
  } 
} 

let a = (5 + 10 * 2 + 15 / 3) * 2 + -10;
let b = (10 + 2) * 30 == 300 + 20 * 3;

if a < 55 {
  if b {
    let c = 55;
  }
}

let d = c + 6;

let double = fn(x) { x + x; };
let triple = fn(x, y) { x + y(x);};
triple(2, double);